In [2]:
import torch
from torch import nn
from d2l import torch as d2l

In [3]:
def batchNormalization(X, gamma, beta, moving_mean, moving_var, eps, momentum):
    if not torch.is_grad_enabled():
        X_hat = (X - moving_mean) / torch.sqrt(moving_var + eps)
    else:
        assert len(X.shape) in (2, 4)
        if len(X.shape) == 2:
            mean = X.mean(dim=0)
            var = ((X - mean)**2).mean(dim=0)
        else:
            mean = X.mean(dim=(0,2,3), keepdims=True)
            var = ((X - mean)**2).mean(dim=(0,2,3),keepdim=True)
        X_hat = (X - mean) / torch.sqrt(var + eps)
        moving_mean = momentum * moving_mean + (1 - momentum) * mean
        moving_var = momentum * moving_var + (1 - momentum) * var
    Y=gamma * X_hat + beta
    return Y, moving_mean, moving_var.data

In [18]:
X = torch.randn(2,2,3)
X

tensor([[[-1.7600,  1.2787,  1.9835],
         [ 1.0104,  0.9450,  1.2862]],

        [[ 0.2103,  0.6154, -1.7522],
         [-0.5461, -2.8473,  1.0881]]])

In [19]:
X.mean(dim=(0,2))

tensor([0.0959, 0.1561])

In [20]:
X[0]

tensor([[-1.7600,  1.2787,  1.9835],
        [ 1.0104,  0.9450,  1.2862]])

In [29]:
torch.cat((X[0][0], X[1][0]),dim=0).mean()
torch.cat((X[0][1], X[1][1]),dim=0).mean()

tensor(0.1561)

$\hat{x}$