In [9]:
import math
%matplotlib
import matplotlib.pyplot as plt
import numpy as np


In [10]:
x = np.linspace(0,10,100)
y1 = np.sin(x)
y2 = np.cos(x)

In [17]:
plt.rcParams['axes.unicode_minus'] = False # 显示负号 
plt.plot(x, y1, label='sin(x)')
plt.plot(x, y2, label='cos(x)')

plt.legend()
plt.show()

In [27]:
arr = np.arange(10)
hasattr(arr,'shape')

True

In [28]:
plt.plot()

[]

In [34]:
# from mxnet import autograd, np, npx
import torch

In [38]:
x = torch.arange(4.0)
print(x)

tensor([0., 1., 2., 3.])


In [41]:
# x.attach_grad()
x.requires_grad_(True)
print(x.grad)

None


In [42]:
y = 2 * torch.dot(x, x)

In [43]:
y

tensor(28., grad_fn=<MulBackward0>)

In [44]:
y.backward()
x.grad

tensor([ 0.,  4.,  8., 12.])

In [46]:
x.grad == 4 * x

tensor([True, True, True, True])

In [47]:
x.grad.zero_()
y = x.sum()
y.backward()
x.grad

tensor([1., 1., 1., 1.])

In [51]:
x.grad.zero_()
y = x * x
y.sum().backward()
x.grad

tensor([0., 2., 4., 6.])

In [61]:
x.grad.zero_()
y = x * x
u = y.detach()
z = u * x
z.sum().backward()
x.grad == u

tensor([True, True, True, True])

In [62]:
x.grad.zero_()
y.sum().backward()
# y.sum().backward()
print(y)
x.grad==2*x

tensor([0., 1., 4., 9.], grad_fn=<MulBackward0>)


tensor([True, True, True, True])

In [83]:
def f(a):
    b = a * 2
    while b.norm() < 1000:
        b = b * 2
    if b.sum() > 0:
        c = b
    else:
        c = 100 * b
    return c

a = torch.randn(size=(2,3), requires_grad=True)
d = f(a)
d.sum().backward()
print(d)
print(d.sum())
print(a)
# a.grad

tensor([[-113136.3281,  -24927.6426,  -84568.7344],
        [  27424.0469,   13761.0469,  -21032.8848]], grad_fn=<MulBackward0>)
tensor(-202480.5000, grad_fn=<SumBackward0>)
tensor([[-2.2097, -0.4869, -1.6517],
        [ 0.5356,  0.2688, -0.4108]], requires_grad=True)


In [79]:
a.grad == d / a

tensor([[ True,  True,  True,  True,  True,  True,  True,  True,  True, False,
          True,  True]])

In [152]:
import math
def g(x):
    return torch.sin(x)

In [131]:
g(math.pi)-0<1e-15

True

In [132]:
import torch
x=torch.arange(0,4,0.1)
print(x)

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000, 1.0000, 1.1000, 1.2000, 1.3000, 1.4000, 1.5000, 1.6000, 1.7000,
        1.8000, 1.9000, 2.0000, 2.1000, 2.2000, 2.3000, 2.4000, 2.5000, 2.6000,
        2.7000, 2.8000, 2.9000, 3.0000, 3.1000, 3.2000, 3.3000, 3.4000, 3.5000,
        3.6000, 3.7000, 3.8000, 3.9000])


In [145]:
import numpy as np
from matplotlib_inline import backend_inline
from d2l import torch as d2l
import matplotlib.pyplot as plt
def use_svg_display():  #@save
    """使用svg格式在Jupyter中显示绘图"""
    backend_inline.set_matplotlib_formats('svg')

def set_figsize(figsize=(3.5, 2.5)):  #@save
    """设置matplotlib的图表大小"""
    use_svg_display()
    d2l.plt.rcParams['figure.figsize'] = figsize

#@save
def set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend):
    """设置matplotlib的轴"""
    axes.set_xlabel(xlabel)
    axes.set_ylabel(ylabel)
    axes.set_xscale(xscale)
    axes.set_yscale(yscale)
    axes.set_xlim(xlim)
    axes.set_ylim(ylim)
    if legend:
        axes.legend(legend)
    axes.grid()

#@save
def plot(X, Y, xlabel=None, ylabel=None, legend=None,
         xlim=None, ylim=None, xscale='linear', yscale='linear',
         fmts=('-','m--', 'g-', 'r:'), figsize=(3.5, 2.5), axes=None):
    if legend is None:
        legend = []
    set_figsize(figsize)
    axes = axes if axes else d2l.plt.gca()

    def has_one_axis(X):
        return hasattr(X, 'ndim') and X.ndim == 1 or isinstance(X, list) and not hasattr(X[0], "__len__")

    if has_one_axis(X):
        X = [X]
    if Y is None:
        X, Y = [[]] * len(X), X
    elif has_one_axis(Y):
        Y = [Y]
    if len(X) != len(Y):
        X = X * len(Y)
    axes.cla()
    for x, y, fmt in zip(X, Y, fmts):
        if len(x):
            axes.plot(x, y, fmt)
        else:
            axes.plot(y, fmt)
    set_axes(axes, xlabel, ylabel, xlim, ylim, xscale, yscale, legend)

ModuleNotFoundError: No module named 'torchvision'

In [ ]:
plot(x,[g(x)],'x','g(x)',legend=['g(x)'])

In [156]:
x=torch.arange(0,1,0.1)
print(x)
x.requires_grad=True
y=g(x)
print(y)
y.sum().backward()
x.grad

tensor([0.0000, 0.1000, 0.2000, 0.3000, 0.4000, 0.5000, 0.6000, 0.7000, 0.8000,
        0.9000])
tensor([0.0000, 0.0998, 0.1987, 0.2955, 0.3894, 0.4794, 0.5646, 0.6442, 0.7174,
        0.7833], grad_fn=<SinBackward0>)


tensor([1.0000, 0.9950, 0.9801, 0.9553, 0.9211, 0.8776, 0.8253, 0.7648, 0.6967,
        0.6216])