In [5]:
from __future__ import unicode_literals, print_function, division
from io import open
import unicodedata
import re
import random
import torch
import torch.nn as nn
from torch import optim
import torch.nn.functional as F

In [3]:
SOS_taken = 0
EOS_taken = 1

In [5]:
class LangEmbed:
    def __init__(self, name):
        self.name = name
        self.word2index = {}
        self.word2count = {}
        self.index2word = {0:'SOS', 1:'EOS'}
        self.n_words = 2
    
    def addSentence(self, sentence):
        for word in sentence.split(' '):
            self.addWord(word)
    
    def addWord(self, word):
        if word not in self.word2index:
            self.word2index[word] = self.n_words
            self.word2count[word] = 1
            self.index2word[self.n_words] = word
            self.n_words += 1
        else:
            self.word2count[word] += 1

In [46]:
t = torch.Tensor([1,2,3])
t

tensor([1., 2., 3.])

In [47]:
t.data

tensor([1., 2., 3.])

In [48]:
t.data == t
t.requires_grad = True
out = t.sigmoid()
d = out.data
d

tensor([0.7311, 0.8808, 0.9526])

In [49]:
d.zero_()
t

tensor([1., 2., 3.], requires_grad=True)

In [58]:
t.sum().backward()

In [59]:
t.grad

tensor([4., 4., 4.])

In [52]:
d.requires_grad

False

In [64]:
a=torch.Tensor([[1,2,3],[2,3,4]])
b=torch.Tensor([[3,4,5],[8,9,10]])
torch.cat((a,b),1)

tensor([[ 1.,  2.,  3.,  3.,  4.,  5.],
        [ 2.,  3.,  4.,  8.,  9., 10.]])

In [76]:
c=torch.randn(4,1,5,1,9,1)

In [77]:
c.shape

torch.Size([4, 1, 5, 1, 9, 1])

In [81]:
c.squeeze(3).shape

torch.Size([4, 1, 5, 9, 1])

In [29]:

a=torch.tensor([[1,2],[3,4]])
a.shape,a.unsqueeze(0).shape,a.unsqueeze(1).shape,a.unsqueeze(2).shape,a.unsqueeze(-1).shape
a.unsqueeze(1)
a.squeeze(1).shape

torch.Size([2, 2])